theme: jekyll-theme-hacker
title: Welcome to the Miran's homepage!
description: Bookmark to stay up to date.
header1: Javascript Junior Develoer
header2: Miran Romick
header2: Address 
header2: City, State, Zip code
